services:
  - type: web
    name: relogio-e-cia
    env: node
    buildCommand: npm ci --omit=dev --ignore-scripts
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeployTrigger: checksPass
